export const AppConfig = {
  width: {
    sideBarCloseBefore: 800,
  },
  reqEndPoints: {
    signUp: '/register',
    signIn: '/login',
    signOut: '/logout',
    uploadCsv: '/csv-upload',
    downloadCsv: '/csv-download',
    uploadAttachmentsAndImages: '/file-upload',
    listHeader: '/header-list',
    editHeader: '/header-edit',
    listData: '/tablewise-list',
    editData: '/tablewise-edit',
    count: '/tablewise-count',
    userRole: '/user-role',
    userAccessList: '/user-access-list',
    editUserAccess: '/edit-user-access',
    adminReview: '/tablewise-edit/review',
  },
  routes: {
    dashboard: '/',
    fieldVists: '/visits/',
    rescue: '/projects/rescue/',
    rehabilitationHome: '/projects/rehab/',
    ecrc: '/projects/ecrc/',
    shelter: '/projects/shelter/',
    otherHomesAdmission: '/projects/otherHomesAdmission/',
    project5A: '/projects/5a/',
    awarenessProgram: '/projects/awareness/',
    humanitarianServices: '/projects/humanitarianServices/',
    outPatientService: '/outPatientService/',
    clients: '/profiles/clients/',
    volunteers: '/profiles/volunteers/',
    informers: '/profiles/informers/',
    staffs: '/profiles/staffs/',
    otherHomes: '/profiles/otherHomes/',
    programTimelines: '/timelines/',
    enquiries: '/enquiries/',
    reports: '/reports/',
    accountSettings: '/accountSettings/',
    detailView: '/detailView/',
  },
  tableRelations: {
    fieldVisitPage: 'fieldVisits',
    projectRescuePage: 'projectRescue',
    projectGobiShelterPage: 'projectGobiShelter',
    projectRehabilitationHomeClientsPage: 'projectRehabilitationHomeClients',
    projectRehabilitationHomeActivityTrackerPage:
      'projectRehabilitationHomeActivityTracker',
    projectRehabilitationHomeFoodMenuPage: 'projectRehabilitationHomeFoodMenu',
    projectRehabilitationHomeVisitorsPage: 'projectRehabilitationHomeVisitors',
    projectECRCPage: 'projectECRC',
    projectAwarenessProgramPage: 'projectAwarenessProgram',
    project5APage: 'project5A',
    projectHumanitarianServicesPage: 'projectHumanitarianServices',
    projectAdmittedToOtherHomesPage: 'projectAdmittedToOtherHomes',
    outPatientServicesPage: 'outPatientServices',
    profilesClientsPage: 'profilesClients',
    profilesVolunteersPage: 'profilesVolunteers',
    profilesInformersPage: 'profilesInformers',
    profilesOtherHomesPage: 'profilesOtherHomes',
    profilesStaffsPage: 'profilesStaffs',
    programTimelinesPage: 'programTimelines',
    enquiriesPage: 'enquiries',
  },
  rehabTabsParams: {
    clients: 'rehabClients',
    activityTracker: 'activityTracker',
    foodMenu: 'foodMenu',
    visitors: 'visitors',
  },
  shelterTabsParams: {
    clients: 'shelterClients',
  },
  awarnessProgramTabs: {
    upcoming: 'Upcoming Events',
    completed: 'Completed Events',
  },
  loginTypes: {},
  tabs: {},
  userRoles: {
    admin: 'admin',
    user: 'user',
  },
};
