export default async function handler(request, response) {
  response.status(200).send({
    response: [
      {
        id: '1',
        gcRegisterNumber: 'GC001',
        type: 'General - Internship',
        callerPhoneNumber: '+91 90067 89090',
        callerName: 'Arun Kumar',
        callerLocation: 'Erode',
        reasonForPhoneCall: 'Special occasion Booking call',
      },
      {
        id: '2',
        gcRegisterNumber: 'GC001',
        type: 'General - Internship',
        callerPhoneNumber: '+91 90067 89090',
        callerName: 'Arun Kumar',
        callerLocation: 'Erode',
        reasonForPhoneCall: 'Special occasion Booking call',
      },
      {
        id: '3',
        gcRegisterNumber: 'GC001',
        type: 'General - Internship',
        callerPhoneNumber: '+91 90067 89090',
        callerName: 'Arun Kumar',
        callerLocation: 'Erode',
        reasonForPhoneCall: 'Special occasion Booking call',
      },
      {
        id: '4',
        gcRegisterNumber: 'GC001',
        type: 'General - Internship',
        callerPhoneNumber: '+91 90067 89090',
        callerName: 'Arun Kumar',
        callerLocation: 'Erode',
        reasonForPhoneCall: 'Special occasion Booking call',
      },
      {
        id: '5',
        gcRegisterNumber: 'GC001',
        type: 'General - Internship',
        callerPhoneNumber: '+91 90067 89090',
        callerName: 'Arun Kumar',
        callerLocation: 'Erode',
        reasonForPhoneCall: 'Special occasion Booking call',
      },
      {
        id: '6',
        gcRegisterNumber: 'GC001',
        type: 'General - Internship',
        callerPhoneNumber: '+91 90067 89090',
        callerName: 'Arun Kumar',
        callerLocation: 'Erode',
        reasonForPhoneCall: 'Special occasion Booking call',
      },
      {
        id: '7',
        gcRegisterNumber: 'GC001',
        type: 'General - Internship',
        callerPhoneNumber: '+91 90067 89090',
        callerName: 'Arun Kumar',
        callerLocation: 'Erode',
        reasonForPhoneCall: 'Special occasion Booking call',
      },
    ],
  });
}
