export default async function handler(request, response) {
  response.status(200).send({
    response: [
      {
        id: '1',
        otRegNo: 'ascwERFEW',
        outreachDate: '10-02-1996',
        auin: 'wfewFWEF',
        clientName: 'Govi',
        age: '25',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '/assets/images/placeholder.png',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '2',
        otRegNo: 'adfvfvrsf',
        outreachDate: '10-04-1996',
        auin: 'wfewFWEF',
        clientName: 'kovi',
        age: '35',
        gender: 'Female',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '/assets/images/placeholder.png',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '3',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '/assets/images/placeholder.png',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '4',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '5',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '/assets/images/placeholder.png',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '6',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '7',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '8',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '9',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '10',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '11',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '12',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '13',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '14',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '15',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
      {
        id: '16',
        otRegNo: 'jknujuyrj',
        outreachDate: '10-11-1996',
        auin: 'wfewFWEF',
        clientName: 'novi',
        age: '45',
        gender: 'Male',
        healthCondition: 'Normal',
        typeOfAddiction: 'Alcohol',
        causeOfBeginning: 'Family issue',
        incomeFromBegging: '<5000',
        educationalQualification: '12th',
        location: 'Kovil Patti',
        photo: '',
        volunteerId: ['arfwef', 'qwrfrewfwr', 'qrfrwf'],
        volunteerNames: ['Naveen', 'Mithun', 'Hassan'],
        status: 'Admitted',
      },
    ],
  });
}
