export default async function handler(request, response) {
  response.status(200).send({
    response: [
      {
        id: '1',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '2',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '3',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '4',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '5',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '6',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '7',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '8',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '9',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '10',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '11',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '12',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
      {
        id: '13',
        informerName: 'Naveen',
        informerContactDetails: '+91 98765 40598',
        informerRelationship: 'Father',
        informerLocation: 'Erode',
        clientName: 'Tamil',
        clientAge: '22',
        clientPhoto: '/assets/images/placeholder.png',
        actionTaken: 'Action Remarks',
      },
    ],
  });
}
