export default async function handler(request, response) {
  response.status(200).send({
    response: [
      {
        id: '1',
        volunteerName: 'Hassan',
        volunteerId: 'VOL0001',
        volunteerPhoto: '/assets/images/placeholder.png',
        contactNumber: '+91 9876533751',
        fatherName: 'Basha',
        qualification: 'B.E.(Mech)',
        bloodGroup: 'B+',
        address: 'new bus stand, ammapet, salem - 636023',
        facebookHandle: 'https://www.facebook.com/hassan.tackler',
        instagramHandle: 'https://www.instagram.com/maybe_am_not_u',
        twitterHandle: 'https://twitter.com/hassan_tackler',
      },
      {
        id: '2',
        volunteerName: 'Hassan',
        volunteerId: 'VOL0001',
        volunteerPhoto: '/assets/images/placeholder.png',
        contactNumber: '+91 9876533751',
        fatherName: 'Basha',
        qualification: 'B.E.(Mech)',
        bloodGroup: 'B+',
        address: 'new bus stand, ammapet, salem - 636023',
        facebookHandle: 'https://www.facebook.com/hassan.tackler',
        instagramHandle: 'https://www.instagram.com/maybe_am_not_u',
        twitterHandle: 'https://twitter.com/hassan_tackler',
      },
      {
        id: '3',
        volunteerName: 'Hassan',
        volunteerId: 'VOL0001',
        volunteerPhoto: '/assets/images/placeholder.png',
        contactNumber: '+91 9876533751',
        fatherName: 'Basha',
        qualification: 'B.E.(Mech)',
        bloodGroup: 'B+',
        address: 'new bus stand, ammapet, salem - 636023',
        facebookHandle: 'https://www.facebook.com/hassan.tackler',
        instagramHandle: 'https://www.instagram.com/maybe_am_not_u',
        twitterHandle: 'https://twitter.com/hassan_tackler',
      },
      {
        id: '4',
        volunteerName: 'Hassan',
        volunteerId: 'VOL0001',
        volunteerPhoto: '/assets/images/placeholder.png',
        contactNumber: '+91 9876533751',
        fatherName: 'Basha',
        qualification: 'B.E.(Mech)',
        bloodGroup: 'B+',
        address: 'new bus stand, ammapet, salem - 636023',
        facebookHandle: 'https://www.facebook.com/hassan.tackler',
        instagramHandle: 'https://www.instagram.com/maybe_am_not_u',
        twitterHandle: 'https://twitter.com/hassan_tackler',
      },
      {
        id: '5',
        volunteerName: 'Hassan',
        volunteerId: 'VOL0001',
        volunteerPhoto: '/assets/images/placeholder.png',
        contactNumber: '+91 9876533751',
        fatherName: 'Basha',
        qualification: 'B.E.(Mech)',
        bloodGroup: 'B+',
        address: 'new bus stand, ammapet, salem - 636023',
        facebookHandle: 'https://www.facebook.com/hassan.tackler',
        instagramHandle: 'https://www.instagram.com/maybe_am_not_u',
        twitterHandle: 'https://twitter.com/hassan_tackler',
      },
      {
        id: '6',
        volunteerName: 'Hassan',
        volunteerId: 'VOL0001',
        volunteerPhoto: '/assets/images/placeholder.png',
        contactNumber: '+91 9876533751',
        fatherName: 'Basha',
        qualification: 'B.E.(Mech)',
        bloodGroup: 'B+',
        address: 'new bus stand, ammapet, salem - 636023',
        facebookHandle: 'https://www.facebook.com/hassan.tackler',
        instagramHandle: 'https://www.instagram.com/maybe_am_not_u',
        twitterHandle: 'https://twitter.com/hassan_tackler',
      },
      {
        id: '7',
        volunteerName: 'Hassan',
        volunteerId: 'VOL0001',
        volunteerPhoto: '/assets/images/placeholder.png',
        contactNumber: '+91 9876533751',
        fatherName: 'Basha',
        qualification: 'B.E.(Mech)',
        bloodGroup: 'B+',
        address: 'new bus stand, ammapet, salem - 636023',
        facebookHandle: 'https://www.facebook.com/hassan.tackler',
        instagramHandle: 'https://www.instagram.com/maybe_am_not_u',
        twitterHandle: 'https://twitter.com/hassan_tackler',
      },
    ],
  });
}
