export default async function handler(request, response) {
  response.status(200).send({
    response: [
      {
        id: '1',
        clientName: 'Siva Kumar',
        clientId: 'AUIN001',
        clientPhoto: '/assets/images/placeholder.png',
        age: '23',
        healthCondition: 'Affected by disease',
        gender: 'Male',
        dateOfRescue: '25-10-2022',
        currentStatus: 'Rejoined with Family',
      },
      {
        id: '2',
        clientName: 'Arun Kumar',
        clientId: 'AUIN002',
        clientPhoto: '/assets/images/placeholder.png',
        age: '26',
        healthCondition: 'Affected by disease',
        gender: 'Male',
        dateOfRescue: '25-10-2022',
        currentStatus: 'Rejoined with Family',
      },
      {
        id: '3',
        clientName: 'Praveen Kumar',
        clientId: 'AUIN003',
        clientPhoto: '/assets/images/placeholder.png',
        age: '23',
        healthCondition: 'Affected by disease',
        gender: 'Male',
        dateOfRescue: '25-10-2022',
        currentStatus: 'Rejoined with Family',
      },
      {
        id: '4',
        clientName: 'Sunil Kumar',
        clientId: 'AUIN004',
        clientPhoto: '/assets/images/placeholder.png',
        age: '23',
        healthCondition: 'Affected by disease',
        gender: 'Male',
        dateOfRescue: '25-10-2022',
        currentStatus: 'Rejoined with Family',
      },
      {
        id: '5',
        clientName: 'Karthick Kumar',
        clientId: 'AUIN005',
        clientPhoto: '/assets/images/placeholder.png',
        age: '23',
        healthCondition: 'Affected by disease',
        gender: 'Male',
        dateOfRescue: '25-10-2022',
        currentStatus: 'Rejoined with Family',
      },
      {
        id: '6',
        clientName: 'Siva Kumar',
        clientId: 'AUIN001',
        clientPhoto: '/assets/images/placeholder.png',
        age: '23',
        healthCondition: 'Affected by disease',
        gender: 'Male',
        dateOfRescue: '25-10-2022',
        currentStatus: 'Rejoined with Family',
      },
      {
        id: '7',
        clientName: 'Siva Kumar',
        clientId: 'AUIN001',
        clientPhoto: '/assets/images/placeholder.png',
        age: '23',
        healthCondition: 'Affected by disease',
        gender: 'Male',
        dateOfRescue: '25-10-2022',
        currentStatus: 'Rejoined with Family',
      },
      {
        id: '8',
        clientName: 'Siva Kumar',
        clientId: 'AUIN001',
        clientPhoto: '/assets/images/placeholder.png',
        age: '23',
        healthCondition: 'Affected by disease',
        gender: 'Male',
        dateOfRescue: '25-10-2022',
        currentStatus: 'Rejoined with Family',
      },
    ],
  });
}
