export default async function handler(request, response) {
  response.status(200).send({
    response: [
      {
        id: '1',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '2',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '3',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '4',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '5',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '6',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '7',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '8',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '9',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '10',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '11',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '12',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '13',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '14',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '15',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
      {
        id: '16',
        clientAdmissionNo: 'OT001',
        admissionDate: '15/08/2023',
        clientsName: 'Raj Kumar',
        age: '56',
        gender: 'Male',
        healthCondition: 'Good',
        rescueLocation: 'Pallipalayam',
        clientNative: 'Pallipalayam',
        clientParentDetail: 'Somu',
        idProof: 'Aadhaar',
        photo: '/assets/images/placeholder.png',
        attachments: '/assets/docs/demo.pdf',
        dateOfAbscond: '12/09/2022',
      },
    ],
  });
}
