export default async function handler(request, response) {
  response.status(200).send({
    response: [
      {
        id: '1',
        clientName: 'Binod',
        foodTaken: 'yes',
        exerciseDone: 'no',
        groomingDone: 'yes',
        readingActivityDone: 'yes',
        remarks: 'Took Medicines',
      },
      {
        id: '2',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '3',
        clientName: 'Nivin',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '4',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '5',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '6',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '7',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '8',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '9',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '10',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '11',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '12',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '13',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '14',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '15',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
      {
        id: '16',
        clientName: 'Vinod',
        foodTaken: 'no',
        exerciseDone: 'yes',
        groomingDone: 'no',
        readingActivityDone: 'yes',
        remarks: 'Skipped  2 pills',
      },
    ],
  });
}
