export default async function handler(request, response) {
  response.status(200).send({
    response: [
      {
        id: '1',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '2',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '3',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '4',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '5',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '6',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '7',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '8',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '9',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '10',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '11',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '12',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '13',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '14',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '15',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
      {
        id: '16',
        visitorName: 'Binod',
        placeOfVisit: 'salem',
        staffAttended: 'kumaaari',
        dateOfVisit: '24-02-2023',
        purposeOfVisit: 'Special occasion Booking call',
        visitorDesignation: 'Engineer',
      },
    ],
  });
}
