export default async function handler(request, response) {
  response.status(200).send({
    response: [
      {
        id: '1',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '2',
        regNo: 'AUIN2323',
        clientName: 'Naveen',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '3',
        regNo: 'AUIN56123',
        clientName: 'Hassan',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '4',
        regNo: 'AUIN7653',
        clientName: 'Ishu',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Female',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '5',
        regNo: 'AUIN129083',
        clientName: 'Anusha',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Female',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '6',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '7',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '8',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '9',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '10',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '11',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '12',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '13',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '14',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '15',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
      {
        id: '16',
        regNo: 'AUIN123',
        clientName: 'Mithun',
        sourcedBy: 'Polimer News',
        age: '25',
        gender: 'Male',
        qualification: 'BE',
        proofs: 'Aadhar',
        rescueLocation: 'Pallipalayam',
        causeOfBegging: 'Family issue',
        healthCondition: 'Good',
        attachments: '/assets/docs/demo.pdf',
        photo: '/assets/images/placeholder.png',
        socialReintegration: 'Rejoined with Family',
      },
    ],
  });
}
