interface DataKeysType {
  key: string;
  type: string;
  len: string;
  fieldType?: string;
}

type DataHeaders = string[];
type DataKeys = DataKeysType[];

export const adminApprovalStatus = {
  'pending approval': 'bg-mild-blue',
  approved: 'bg-light-green',
  deleted: 'bg-red-300 line-through',
  'need changes': 'bg-orange',
};

export const fieldVisitsHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  'OT Reg No',
  'Outreach Date',
  'Client’s Name',
  'Age',
  'Gender',
  'Health Condition',
  'Type of Addiction',
  'Cause of Beginning',
  'Income from Begging',
  'Education Qualification',
  'Location',
  'Photo',
  'Name of the Volunteers',
  'Status',
];

export const fieldVistitsDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'ot_regno', type: 'string', len: '50' },
  { key: 'outreach_date', type: 'date', len: '50' },
  { key: 'client_name', type: 'string', len: '100' },
  { key: 'age', type: 'string', len: '50' },
  { key: 'gender', type: 'string', len: '50' },
  { key: 'health_condition', type: 'string', len: '200' },
  { key: 'type_of_addiction', type: 'string', len: '200' },
  { key: 'cause_of_beginning', type: 'string', len: '200' },
  { key: 'income_from_begging', type: 'string', len: '50' },
  { key: 'education_qualification', type: 'string', len: '200' },
  { key: 'location_address', type: 'string', len: '400' },
  { key: 'client_pic', type: 'image', len: '' },
  { key: 'service_providing_details', type: 'string', len: '400' },
];

export const projectRescueHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  'Reg No',
  'Client’s Name',
  'Sourced By',
  'Age',
  'Gender',
  'Educational Qualification',
  'ID Proofs',
  'Rescue Location',
  'Cause of Begging',
  'Health Condition',
  'Attachments',
  'Photo',
  'Social Reintegration',
];

export const projectRescueDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'regno', type: 'string', len: '50' },
  { key: 'rescue_date', type: 'date', len: '100' },
  { key: 'client_name', type: 'string', len: '100' },
  { key: 'age', type: 'string', len: '50' },
  { key: 'gender', type: 'string', len: '50' },
  { key: 'health_condition', type: 'string', len: '400' },
  { key: 'rescue_location', type: 'string', len: '400' },
  { key: 'education_qualification', type: 'string', len: '200' },
  { key: 'id_proofs', type: 'string', len: '100' },
  { key: 'family_details', type: 'string', len: '400' },
  { key: 'social_reintegration', type: 'string', len: '200' },
  { key: 'client_pic', type: 'image', len: '' },
  { key: 'attachments', type: 'doc', len: '' },
];

export const projectShelterClientsHeader: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  'Client Admission No',
  'Admission Date',
  'Client’s Name',
  'Age',
  'Gender',
  'Health Condition',
  'Rescue Location',
  'Client Native',
  'Client’s Parents Details',
  'ID Proofs',
  'Photo',
  'Attachments',
  'Date of Abscond',
];

export const projectShelterClientsDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'client_admission_no', type: 'string', len: '50' },
  { key: 'admission_date', type: 'date', len: '50' },
  { key: 'client_name', type: 'string', len: '100' },
  { key: 'age', type: 'string', len: '50' },
  { key: 'gender', type: 'string', len: '50' },
  { key: 'health_condition', type: 'string', len: '400' },
  { key: 'rescue_location', type: 'string', len: '400' },
  { key: 'client_native', type: 'string', len: '200' },
  { key: 'client_parent_details', type: 'string', len: '100' },
  { key: 'id_proofs', type: 'string', len: '400' },
  { key: 'client_pic', type: 'image', len: '' },
  { key: 'attachments', type: 'doc', len: '' },
  { key: 'date_of_abscond', type: 'date', len: '' },
];

export const projectRehabClientsHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  'Client Admission No',
  'Admission Date',
  'Client’s Name',
  'Age',
  'Gender',
  'Health Condition',
  'Rescue Location',
  'Client Native',
  'Client’s Parents Details',
  'ID Proofs',
  'Photo',
  'Attachments',
  'Date of Abscond',
];

export const projectRehabClientsDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'client_admission_no', type: 'string', len: '50' },
  { key: 'admission_date', type: 'date', len: '50' },
  { key: 'client_name', type: 'string', len: '100' },
  { key: 'age', type: 'string', len: '50' },
  { key: 'gender', type: 'string', len: '50' },
  { key: 'health_condition', type: 'string', len: '400' },
  { key: 'rescue_location', type: 'string', len: '400' },
  { key: 'client_native', type: 'string', len: '200' },
  { key: 'client_parent_details', type: 'string', len: '100' },
  { key: 'id_proofs', type: 'string', len: '400' },
  { key: 'client_pic', type: 'image', len: '' },
  { key: 'attachments', type: 'doc', len: '' },
  { key: 'date_of_abscond', type: 'date', len: '' },
];

export const projectRehabActivityTrackerHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  'Client’s Name',
  'Food Taken',
  'Exercise Done',
  'Grooming Done',
  'Reading Activity Done',
  'Remarks',
  'Skill Development',
];

export const projectRehabActivityTrackerDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'regno', type: 'string', len: '50' },
  { key: 'admission_date', type: 'date', len: '100' },
  { key: 'client_name', type: 'string', len: '100' },
  { key: 'age', type: 'string', len: '50' },
  { key: 'gender', type: 'string', len: '50' },
  { key: 'health_condition', type: 'string', len: '400' },
  { key: 'rescue_location', type: 'string', len: '400' },
  { key: 'family_details', type: 'string', len: '400' },
  { key: 'food_taken', type: 'string', len: '10' },
  { key: 'medicine_taken', type: 'string', len: '10' },
  { key: 'exercise_status', type: 'string', len: '10' },
  { key: 'grooming_status', type: 'string', len: '10' },
  { key: 'abscond_date', type: 'date', len: '100' },
  { key: 'social_reintegration', type: 'string', len: '200' },
  { key: 'attachments', type: 'string', len: '800' },
  { key: 'client_pic', type: 'string', len: '800' },
];

export const projectRehabVisitorsHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  'Visitor’s Name',
  'Date of Visit',
  'Visitor’s Designation',
  'Place of Visit',
  'Staff Attended',
  'Purpose of Visit',
];

export const projectRehabVisitorsDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'visitor_name', type: 'string', len: '200' },
  { key: 'date_of_visit', type: 'date', len: '' },
  { key: 'visitor_designation', type: 'string', len: '100' },
  { key: 'place_of_visit', type: 'string', len: '400' },
  { key: 'staff_attended', type: 'string', len: '200' },
  { key: 'pupose_of_visit', type: 'string', len: '400' },
  { key: 'contact_no', type: 'string', len: '100' },
];

export const ecrcHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  'Client Admission No',
  'Admission Date',
  'Client’s Name',
  'Age',
  'Gender',
  'Health Condition',
  'Type of Disorder',
  'Type of Diagnosis',
  'Rescue Location',
  'Client Native',
  'Client’s Parents Details',
  'ID Proofs',
  'Photo',
  'Treatment Taken',
  'Medicine Taken',
  'Skill Development Provided',
  'Attachments',
  'Rehabilitation Status',
  'Date of abscond',
];

export const ecrcDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'client_admission_no', type: 'string', len: '50' },
  { key: 'admission_date', type: 'date', len: '' },
  { key: 'client_name', type: 'string', len: '200' },
  { key: 'age', type: 'string', len: '50' },
  { key: 'gender', type: 'string', len: '50' },
  {
    key: 'health_condition',
    type: 'dropDown',
    fieldType: 'string',
    len: '200',
  },
  { key: 'type_of_disorder', type: 'string', len: '200' },
  { key: 'type_of_diagnosis', type: 'string', len: '400' },
  { key: 'rescue_location', type: 'string', len: '400' },
  { key: 'client_native', type: 'string', len: '200' },
  { key: 'client_parent_details', type: 'string', len: '300' },
  { key: 'id_proofs', type: 'string', len: '400' },
  { key: 'client_pic', type: 'image', len: '' },
  { key: 'treatment_taken', type: 'string', len: '400' },
  { key: 'medicine_taken', type: 'string', len: '400' },
  { key: 'skill_development_provided', type: 'string', len: '400' },
  { key: 'attachments', type: 'string', len: '' },
  { key: 'rehabilitation_status', type: 'string', len: '200' },
  { key: 'date_of_abscond', type: 'date', len: '' },
];

export const outPatientServiceHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  "Informer's Name",
  "Informer's Contact Details",
  "Informer's Relationship",
  "Informer's Location",
  'Client’s Name',
  'Client’s Age',
  'Client’s Photo',
  'Action Taken',
];

export const outPatientServiceDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'informer_id', type: 'string', len: '50' },
  { key: 'informer_date', type: 'date', len: '50' },
  { key: 'op_person_name', type: 'string', len: '200' },
  { key: 'age', type: 'string', len: '50' },
  { key: 'gender', type: 'string', len: '50' },
  { key: 'health_condition', type: 'string', len: '200' },
  { key: 'consent_relative', type: 'string', len: '200' },
  { key: 'informer_contact_detail', type: 'string', len: '200' },
  { key: 'informer_location', type: 'string', len: '500' },
  { key: 'informer_relationship', type: 'string', len: '500' },
  { key: 'client_pic', type: 'image', len: '800' },
  { key: 'attachments', type: 'doc', len: '800' },
  { key: 'action_taken', type: 'string', len: '500' },
];

export const enquiriesServiceHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  'S.no',
  'Date',
  'Informer Name',
  'Informer Address',
  'Informer Contact Detail',
  'Reason For The Call',
  'Homeless Person Name',
  'Age',
  'Gender',
  'Health Condition',
  'Status',
  'Photo',
];

export const enquiriesServiceDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'gc_register_number', type: 'string', len: '50' },
  { key: 'enquire_date', type: 'date', len: '50' },
  { key: 'caller_name', type: 'string', len: '200' },
  { key: 'caller_location', type: 'string', len: '400' },
  { key: 'caller_phone_no', type: 'string', len: '200' },
  { key: 'homeless_person_name', type: 'string', len: '400' },
  { key: 'age', type: 'string', len: '3' },
  { key: 'gender', type: 'string', len: '10' },
  { key: 'health_condition', type: 'string', len: '400' },
  { key: 'homeless_person_location', type: 'string', len: '400' },
  { key: 'pic', type: 'image', len: '' },
  { key: 'service_providing_details', type: 'string', len: '800' },
  {
    key: 'volunteer_accommodation',
    type: 'array',
    fieldType: 'string',
    len: '2048',
  },
];

export const reportsHeaders: DataHeaders = [
  'Metrics',
  'Male',
  'Female',
  'Age (20-50)',
  'Age (> 50)',
  'Location - Erode',
];

export const reportsDataKeys: DataKeys = [
  { key: 'metrics', type: 'string' },
  { key: 'male', type: 'string' },
  { key: 'female', type: 'string' },
  { key: 'age20To50', type: 'string' },
  { key: 'ageGreaterThan50', type: 'string' },
  { key: 'locationInErode', type: 'string' },
];

export const profileInformersHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  "Informer's ID",
  "Informer's Name",
  "Informer's Contact Details",
  "Informer's Designation",
  "Informer's Native",
  'Reference',
];

export const profileInformersDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'informer_id', type: 'string', len: '50' },
  { key: 'date_of_info', type: 'date', len: '20' },
  { key: 'informer_name', type: 'string', len: '200' },
  { key: 'contact_details', type: 'string', len: '100' },
  { key: 'informer_designation', type: 'string', len: '200' },
  { key: 'informer_native', type: 'string', len: '200' },
];

export const admittedInOtherHomesHeaders: DataHeaders = [
  'Select Action',
  'Approval Status',
  'Admin Remarks',
  'Record Created On',
  'S.no',
  'Date',
  'Rescue Person Name',
  'Age',
  'Gender',
  'Health Condition',
  'Rescue Place',
  'Photo',
  'Admitted Home Name',
  'Home Address',
  'Staff Accommodation',
  'Volunteer Accommodation',
  '1st follow up',
  '2nd follow up',
  '3rd follow up',
  '4th follow up',
];

export const admittedInOtherHomesDataKeys: DataKeys = [
  { key: 'approval_status', type: 'string', len: '50' },
  { key: 'admin_remarks', type: 'string', len: '400' },
  { key: 'created_at', type: 'date', len: '' },
  { key: 'ot_regno', type: 'string', len: '50' },
  { key: 'outreach_date', type: 'date', len: '50' },
  { key: 'client_name', type: 'string', len: '100' },
  { key: 'age', type: 'string', len: '50' },
  { key: 'gender', type: 'string', len: '50' },
  { key: 'health_condition', type: 'string', len: '200' },
  { key: 'rescue_address', type: 'string', len: '400' },
  { key: 'client_pic', type: 'image', len: '' },
  { key: 'home_name', type: 'string', len: '400' },
  { key: 'home_address', type: 'string', len: '800' },
  { key: 'admit_date', type: 'date', len: '50' },
  { key: 'staff_accommodation', type: 'string', len: '800' },
  { key: 'volunteer_accommodation', type: 'string', len: '800' },
  { key: 'first_month_follow_up', type: 'string', len: '2048' },
  { key: 'second_month_follow_up', type: 'string', len: '2048' },
  { key: 'third_month_follow_up', type: 'string', len: '2048' },
  { key: 'fourth_month_follow_up', type: 'string', len: '2048' },
];
